# Generated by Django 5.2.10 on 2026-01-18 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0003_safetycheck_waterplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('data_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.groundwaterdata')),
            ],
        ),
    ]
