# Generated by Django 5.2.10 on 2026-02-15 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        ('portal', '0004_groundwaterdata_latitude_groundwaterdata_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmarker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mapmarker',
            name='data_point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marker', to='portal.groundwaterdata'),
        ),
    ]
