# Generated by Django 5.2.10 on 2026-01-18 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundwaterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('status_category', models.CharField(choices=[('Safe', 'Safe'), ('Semi-Critical', 'Semi-Critical'), ('Critical', 'Critical'), ('Over-Exploited', 'Over-Exploited')], default='Safe', max_length=20)),
                ('extraction_percentage', models.FloatField(default=0.0)),
                ('recharge_value', models.FloatField(default=0.0)),
                ('description', models.TextField(help_text='Details about local water stress or alerts')),
                ('is_active_alert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Groundwater Data',
                'verbose_name_plural': 'Groundwater Data Entries',
            },
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
