# Generated by Django 5.2.10 on 2026-01-18 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_groundwaterdata_delete_incident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_area', models.CharField(help_text='Area or Landmark', max_length=100)),
                ('source_type', models.CharField(choices=[('borewell', 'Borewell'), ('well', 'Open Well'), ('tap', 'Public Supply / Tap'), ('tanker', 'Private Tanker')], max_length=20)),
                ('safety_score', models.CharField(max_length=20)),
                ('advice', models.TextField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_size', models.FloatField(help_text='Size in Acres')),
                ('crop_type', models.CharField(choices=[('paddy', 'Paddy / Rice'), ('wheat', 'Wheat'), ('maize', 'Maize / Corn'), ('millets', 'Millets'), ('vegetables', 'Vegetables')], max_length=50)),
                ('season', models.CharField(choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('summer', 'Summer')], max_length=20)),
                ('estimated_need', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(default='Low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
