# Generated by Django 5.2.10 on 2026-01-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_safetycheck_waterplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundwaterdata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groundwaterdata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
