# Generated by Django 5.2.10 on 2026-02-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_groundwaterdata_latitude_groundwaterdata_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundwaterdata',
            name='assessment_year',
            field=models.IntegerField(default=2023),
        ),
    ]
