# Generated by Django 5.1.6 on 2026-03-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_groundwaterdata_assessment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundwaterdata',
            name='description',
            field=models.TextField(help_text='Details about groundwater conditions'),
        ),
        migrations.AlterField(
            model_name='waterplan',
            name='land_size',
            field=models.FloatField(help_text='Size of land in Acres'),
        ),
    ]
