# Generated by Django 5.2.10 on 2026-01-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('benefits', models.TextField(help_text='Bulleted list of benefits')),
                ('eligibility', models.TextField()),
                ('application_link', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('irrigation', 'Irrigation Support'), ('financial', 'Financial Subsidy'), ('technical', 'Technical Assistance'), ('infrastructure', 'Rainwater Harvesting')], max_length=50)),
                ('state_specific', models.CharField(blank=True, help_text='Leave blank for National schemes', max_length=100)),
            ],
        ),
    ]
