# Generated by Django 5.2.10 on 2026-01-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatconversation',
            name='language',
        ),
    ]
