# Generated by Django 5.2.10 on 2026-01-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_chatconversation_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
