# Generated by Django 5.2.10 on 2026-01-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatconversation_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='bot_type',
            field=models.CharField(choices=[('public', 'Public Groundwater Bot'), ('official', 'Official Policy Bot')], default='public', max_length=10),
        ),
    ]
