# Generated by Django 5.2.10 on 2026-01-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_chatconversation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatconversation',
            name='language',
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
