from django.db import models
from django.conf import settings

class GroundwaterReport(models.Model):
    """
    Acts as the 'Scientific Output' node for INGRES-AI.
    Stores multi-year snapshots for Researchers and Official oversight.
    """
    REPORT_TYPES = [
        ('trend', 'Multi-Year Trend Analysis'),
        ('comparative', 'Regional Comparative Analysis'),
        ('extraction', 'Extraction Stage Summary'),
    ]

    # Links the report to the user who generated it
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        related_name='reports'
    )
    
    # Metadata for the report
    title = models.CharField(max_length=255, help_text="e.g., Guntur District 2020-2024 Trend")
    report_type = models.CharField(max_length=20, choices=REPORT_TYPES)
    district = models.CharField(max_length=100)
    state = models.CharField(max_length=100, default="Andhra Pradesh")
    
    # The Core Data: JSONField stores the specific numbers used for the charts
    # This ensures FR-2.4 (Data Integrity) is maintained in the snapshot.
    data_payload = models.JSONField(
        help_text="Stores chart labels, extraction percentages, and recharge values."
    )
    
    # Summary generated by the logic (or AI interpretation)
    summary_notes = models.TextField(blank=True, null=True)
    
    generated_at = models.DateTimeField(auto_now_add=True)
    is_archived = models.BooleanField(default=False)

    class Meta:
        ordering = ['-generated_at']
        verbose_name = "Groundwater Intelligence Report"
        verbose_name_plural = "Groundwater Intelligence Reports"

    def __str__(self):
        return f"{self.district} | {self.get_report_type_display()} | {self.generated_at.strftime('%Y-%m-%d')}"

    @property
    def fiscal_range(self):
        """Returns the year range of the report if data exists."""
        if 'labels' in self.data_payload and self.data_payload['labels']:
            return f"{self.data_payload['labels'][0]} - {self.data_payload['labels'][-1]}"
        return "Unknown Range"