# Generated by Django 5.2.10 on 2026-02-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('public', 'Public User (Citizen/Farmer)'), ('researcher', 'Research / Academic User'), ('official', 'Official Government User')], default='public', max_length=15),
        ),
    ]
