# Generated by Django 5.1.6 on 2026-03-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_role_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchDomainWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='e.g., institution.edu, org.name.org', max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('public', 'Public User (Citizen/Farmer)'), ('researcher', 'Research / Academic User'), ('official', 'Official Government User')], default='official', max_length=15),
        ),
    ]
