# Generated by Django 5.2.10 on 2026-02-15 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundwaterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Guntur District 2020-2024 Trend', max_length=255)),
                ('report_type', models.CharField(choices=[('trend', 'Multi-Year Trend Analysis'), ('comparative', 'Regional Comparative Analysis'), ('extraction', 'Extraction Stage Summary')], max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Andhra Pradesh', max_length=100)),
                ('data_payload', models.JSONField(help_text='Stores chart labels, extraction percentages, and recharge values.')),
                ('summary_notes', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Groundwater Intelligence Report',
                'verbose_name_plural': 'Groundwater Intelligence Reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
